### ISSUE TITLE
Support for Linux arm64 execution platform

### ISSUE THREAD

**Issue by juanzolotoochin** [bazel-contrib/musl-toolchain#37]
It seems that this toolchain does not work when running on `arm64`. I couldn't find information on the README about whether this is expected to work or not, I may be doing something wrong.

I'd like to be able to compile from Linux `arm64` to both `arm64` and `x86_64`

**Comment by fmeum** [comment]
Linux arm64 is currently not supported as an execution platform, simply because OSS repos [can't use GitHub's Linux arm64 runners yet](https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/#get-started-using-arm-hosted-runners-today). When that changes, we can probably add support very easily.

I will check whether there are any alternatives.
